import { useState } from "react";
import { Activity, Pencil, Search, Trash2 } from "lucide-react";
import { Badge, Field, FormActions, Modal, PageHeader, SelectField } from "../components/UI";
import { useLifeLog } from "../data/LifeLogContext";

const blank={name:"",category:"Study",location:"College",time:"09:00",duration:"1h",date:"2026-09-07"};
export default function Activities(){
 const {activities,add,remove,update}=useLifeLog(); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [search,setSearch]=useState(""); const [category,setCategory]=useState("All categories"); const [form,setForm]=useState(blank);
 const filtered=activities.filter(x=>(x.name.toLowerCase().includes(search.toLowerCase())||x.category.toLowerCase().includes(search.toLowerCase()))&&(category==="All categories"||x.category===category));
 function submit(e){e.preventDefault(); if(!form.name.trim()) return; editing?update('activities',editing,{...form}):add('activities',{...form}); setOpen(false);setEditing(null);setForm(blank);}
 function edit(x){setEditing(x.id);setForm({...x});setOpen(true)}
 return <div><PageHeader title="Activities" description="Capture the moments that make up your day." action={()=>{setEditing(null);setForm(blank);setOpen(true)}} actionLabel="Add activity" icon={Activity}/>
 <div className="card overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-4 sm:flex-row"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input className="input pl-9" placeholder="Search activities..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="input w-auto" value={category} onChange={e=>setCategory(e.target.value)}><option>All categories</option>{["Study","Work","Exercise","Travel","Social","Personal","Entertainment"].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Activity</th><th>Category</th><th>Location</th><th>Date</th><th>Time</th><th>Duration</th><th className="pr-5">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(x=><tr key={x.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 font-semibold">{x.name}</td><td><Badge tone={x.category==="Study"?"blue":x.category==="Exercise"?"green":"slate"}>{x.category}</Badge></td><td className="text-slate-500">{x.location}</td><td className="text-slate-500">{x.date}</td><td className="text-slate-500">{x.time} – {x.end||"—"}</td><td className="text-slate-500">{x.duration}</td><td className="pr-5"><button onClick={()=>edit(x)} title="Edit" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><Pencil size={15}/></button><button onClick={()=>remove('activities',x.id)} title="Delete" className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit activity":"Add activity"}><form onSubmit={submit} className="space-y-4"><Field label="Activity name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. SQL Practice"/><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Study","Work","Exercise","Travel","Social","Personal","Entertainment"].map(x=><option key={x}>{x}</option>)}</SelectField><Field label="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Date" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><Field label="Start time" type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/><Field label="Duration" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})} placeholder="e.g. 1h 30m"/></div><FormActions onCancel={()=>setOpen(false)} submit={editing?"Update":"Save"}/></form></Modal>
 </div>
}
